<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PrathibaSuresh" ignored="0" name="RetryMultipleFailedTestcases" tests="8" failures="2" timestamp="30 Mar 2021 08:02:18 GMT" time="0.09" errors="0">
  <testcase name="Test1" time="0.016" classname="Test_Retry_Logic.MyTest1">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="Test_Retry_Logic.MyTest1">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="Test_Retry_Logic.MyTest1">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="Test_Retry_Logic.MyTest1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at Test_Retry_Logic.MyTest1.Test1(MyTest1.java:13)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.002" classname="Test_Retry_Logic.MyTest1">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="Test_Retry_Logic.MyTest1">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="Test_Retry_Logic.MyTest1">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="Test_Retry_Logic.MyTest1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at Test_Retry_Logic.MyTest1.Test2(MyTest1.java:19)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- RetryMultipleFailedTestcases -->
